version: '2'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: vessel/app
    environment:
      CONTAINER_ENV: "${APP_ENV}"
      XDEBUG_HOST: "${XDEBUG_HOST}"
      WWWUSER: "${WWWUSER}"
    volumes:
      - .:/var/www/html
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.mini-crm.rule=Host(`crm.shaiful.my`)'
      - 'traefik.http.routers.mini-crm.entrypoints=websecure'
      - 'traefik.http.services.mini-crm.loadbalancer.server.port=80'
      - 'traefik.docker.network=web'
      - "traefik.http.routers.mini-crm.tls.certresolver=myresolver"
    networks:
      - vessel
      - web
      - mariadb_database
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
      args:
        uid: "${WWWUSER}"
    image: vessel/node
    user: node
    volumes:
     - .:/var/www/html
    networks:
     - vessel
  mysql:
    image: mysql:5.7
    ports:
     - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
     - vesselmysql:/var/lib/mysql
     # - ./docker/mysql/conf.d:/etc/mysql/conf.d
     # - ./docker/mysql/logs:/var/log/mysql
    networks:
     - vessel
  redis:
    image: redis:alpine
    volumes:
     - vesselredis:/data
    networks:
     - vessel
networks:
  vessel:
    driver: "bridge"
  web:
    external: true
  mariadb_database:
    external: true
volumes:
  vesselmysql:
    driver: "local"
  vesselredis:
    driver: "local"
